services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: didakt_user
      POSTGRES_PASSWORD: didakt_pass
      POSTGRES_DB: didakt
    volumes:
      - postgres-data:/var/lib/postgresql/data

  didakt.api.auth:
    build:
      context: ./Didakt.Api.Auth
      dockerfile: Dockerfile
    ports:
      - "5224:8080"
    environment:
      - ConnectionStrings__Postgres=Host=postgres;Database=didakt;Username=didakt_user;Password=didakt_pass
    depends_on:
      - postgres

  didakt.api.leaderboard:
    build:
      context: ./Didakt.Api.Leaderboard
      dockerfile: Dockerfile
    ports:
      - "5223:8080"
    environment:
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - redis
volumes:
  redis-data:
  postgres-data: