@leaderboard_service_HostAddress = http://localhost:5223

POST {{leaderboard_service_HostAddress}}/leaderboard/testGame/score
Content-Type: application/json

{
  "player": "bill",
  "score": 9500
}

###
